client_config_backend: file
client_config_file: client_secrets.json
save_credentials: False
save_credentials_backend: file
save_credentials_file: credentials.txt
oauth_scope:
  - 'https://www.googleapis.com/auth/userinfo.email'
  - 'https://www.googleapis.com/auth/drive'
  - 'https://www.googleapis.com/auth/drive.file'
  - 'https://www.googleapis.com/auth/drive.readonly'
  - 'https://www.googleapis.com/auth/drive.metadata.readonly'
